name: test-variable-passing-across-jobs
on:
  workflow_dispatch:
    inputs:
      re-run-status:
        required: true
        type: choice
        options:
          - success
          - fail

jobs:
  Django-test:
    name: Django-test
    runs-on: ubuntu-latest

    outputs:
      test-outcome: ${{ steps.see-output-in-next-step.outputs.result }}

    steps:
      - name: Rerun failed tests
        id: django-failed-tests-rerun
        continue-on-error: true
        run: |
          if [ "${{ github.event.inputs.re-run-status }}" = "fail" ]; then
            echo "test-result=fail" >> $GITHUB_ENV
            exit 1
          else
            echo "test-result=success" >> $GITHUB_ENV
          fi

      - name: Set step output
        id: see-output-in-next-step
        continue-on-error: true
        run: |
          echo "::set-output name=result::${{ env.test-result }}"

  PublishTestResults:
    name: Publish unit test results
    needs: Django-test
    if: always()
    runs-on: ubuntu-latest

    steps:
      - name: Display the test result
        run: |
          echo "Outcome of Django-test: ${{ needs.Django-test.outputs.test-outcome }}"
